[tests] Remove load_orgs testing because it fails in Travis
RuntimeError: Lost connection to MySQL server during query (err: 2013)

To avoid this error I have tried the normal config vars in MySQL:

net_read_timeout=180
net_write_timeout=180
max_allowed_packet=16M
wait_timeout=2592000
interactive_timeout=2592000
max_connections=300

but no luck.